
import numpy as np
import matplotlib.pyplot as plt
import sys
import os
import torch

import torch.nn as nn

sys.path.append('../../')
# sys.path.append(os.path.join(os.getcwd(), 'pykan'))
# import pykan.kan as KAN

import pykan.kan as KAN

# load the npz file generated by 1D_plasticity.py
data = np.load("1D_plasticity_results.npz")

eps = data["eps"][0:50]
sigma = data["sigma"][0:50]

# normalize to [0,1]
eps_min, eps_max = eps.min(), eps.max()
sigma_min, sigma_max = sigma.min(), sigma.max()
eps_norm = eps / eps_max
sigma_norm = sigma / sigma_max

eps = eps_norm
sigma = sigma_norm

# Plot the normalized results
plt.plot(eps, sigma, label="Truth (normalized)", marker='o')
plt.xlabel("Strain (normalized)")
plt.ylabel("Stress (normalized)")


#############################################################################
#############################################################################
#############################################################################
#############################################################################

class KANStressPredictor(nn.Module):

    def __init__(self):
        super(KANStressPredictor, self).__init__()

        self.kappa = torch.tensor(0.0) # dissipation
        self.q = torch.tensor(0.0)     # plastic strain

        self.model_psi = KAN.MultKAN( # eps, q, kappa --> psi // stress = grad.psi
            width=[3, 2, 1],
            grid=3,
            k=2,
            grid_range=[0, 1]
        )
        self.model_psi.speed()
        
        self.model_F = KAN.MultKAN( # eps, kappa --> F
            width=[2, 1, 1],
            grid=3,
            k=2,
            grid_range=[0, 1]
        )
        self.model_F.speed()

    def forward(self, strain):

        strain = strain.detach().requires_grad_(True)

        psi_KAN_inputs = []
        psi_KAN_inputs.append(strain)
        psi_KAN_inputs.append(torch.full_like(strain, self.q))
        psi_KAN_inputs.append(torch.full_like(strain, self.kappa))

        KAN_input = torch.cat(psi_KAN_inputs, dim=-1)

        # This method computes the stress without updating internal vars
        zeros = torch.zeros_like(KAN_input, requires_grad=True)

        raw_psi = self.model_psi(KAN_input)
        psi_at_0 = self.model_psi(zeros)
        
        grad_0 = torch.autograd.grad(
            outputs=psi_at_0,
            inputs=zeros,
            grad_outputs=torch.ones_like(psi_at_0),
            create_graph=True
        )[0]

        grad = torch.autograd.grad(
            outputs=raw_psi,
            inputs=strain,
            grad_outputs=torch.ones_like(raw_psi),
            create_graph=True
        )[0]

        return grad - grad_0[:, :1] # grad_0[:, :1] selects the first column of strain, shape (100, 1)

    def FinalizeMaterialResponse(self, strain):
        pass


    def ResetInternalVars(self):
        self.kappa = torch.tensor(0.0) # dissipation
        self.q = torch.tensor(0.0)     # plastic strain

#############################################################################
#############################################################################
#############################################################################
#############################################################################


model = KANStressPredictor()

optimizer = torch.optim.Adam(model.parameters(), lr=0.01)

x_torch = torch.tensor(eps, dtype=torch.float32).unsqueeze(1)  # (steps,1)
y_torch = torch.tensor(sigma, dtype=torch.float32).unsqueeze(1)  # (steps,1)
zeros = torch.zeros_like(x_torch)

n_epochs = 150

for epoch in range(n_epochs):
    optimizer.zero_grad()

    vectorized = False

    if vectorized:
        y_pred = model(x_torch)  # shape (100,1)
    else:
        y_pred_list = []
        for i in range(len(x_torch)):
            x_i = x_torch[i].view(1, 1)  # already tensor, no need to recreate
            y_pred_i = model(x_i)        # keep tensor with grad
            y_pred_list.append(y_pred_i)

        # Stack into a tensor
        y_pred = torch.vstack(y_pred_list)  # shape (100,1)


    # L2 loss
    loss = torch.mean((y_pred - y_torch)**2)

    loss.backward()
    optimizer.step()

    if epoch % 2 == 0:
        print(f"Epoch {epoch}, Loss: {loss.item()}")

# plot the KAN
y_KAN = model(x_torch).detach().numpy().flatten()

plt.plot(eps, y_KAN, '--', color="k", label='KAN (trained)')
plt.legend()
plt.grid()
plt.show()