
import numpy as np
import matplotlib.pyplot as plt

import pykan.kan as KAN

# load the npz file generated by 1D_plasticity.py
data = np.load("1D_plasticity_results.npz")

eps = data["eps"]
sigma = data["sigma"]

# Plot the results
plt.plot(eps, sigma, label="Truth")
plt.xlabel("Strain")
plt.ylabel("Stress")
plt.legend()
plt.grid()


#-----------------------------
# Create surrogate model
model = KAN.MultKAN( # x--[]-->y
    width=[1, 1],
    grid=6,
    k=3,
    grid_range=[-0.02, 0.02]
)
model.speed()

optimizer = torch.optim.Adam(model.parameters(), lr=0.01)

x_torch = torch.tensor(eps, dtype=torch.float32).unsqueeze(1)  # (steps,1)
y_torch = torch.tensor(sigma, dtype=torch.float32).unsqueeze(1)  # (steps,1)

n_epochs = 4000

for epoch in range(n_epochs):
    optimizer.zero_grad()

    # y_pred_list = []
    # for i in range(len(x)):
    #     x_i = x_torch[i].view(1, 1)  # already tensor, no need to recreate
    #     y_pred_i = model(x_i)        # keep tensor with grad
    #     y_pred_list.append(y_pred_i)

    y_pred = model(x_torch)  # shape (100,1)

    # Stack into a tensor
    # y_pred = torch.vstack(y_pred_list)  # shape (100,1)

    # L2 loss
    loss = torch.mean((y_pred - y_torch)**2)

    loss.backward()
    optimizer.step()

    if epoch % 20 == 0:
        print(f"Epoch {epoch}, Loss: {loss.item()}")













plt.show()