
import numpy as np
import matplotlib.pyplot as plt
import sys
import os
import torch

import torch.nn as nn

sys.path.append('../../')


sys.path.append(os.path.join(os.getcwd(), 'pykan'))
import pykan.kan as KAN




# sys.path.append(os.path.join(os.getcwd(), '../../ICKANs'))
# import ICKANs.ickan as KAN





# load the npz file generated by 1D_plasticity.py
data = np.load("1D_plasticity_results.npz")

n_final_step = 100
eps = data["eps"][0:n_final_step]
sigma = data["sigma"][0:n_final_step]

# normalize to [0,1]
eps_min, eps_max = eps.min(), eps.max()
sigma_min, sigma_max = sigma.min(), sigma.max()
eps_norm = eps / eps_max
sigma_norm = sigma / sigma_max

eps = eps_norm
sigma = sigma_norm

# Plot the normalized results
plt.plot(eps, sigma, label="Truth (normalized)", marker='o', color="green")
plt.xlabel("Strain (normalized)")
plt.ylabel("Stress (normalized)")

def atan_regularization(raw_value, k=1):
    return torch.atan(k * raw_value) / np.pi # + 0.5, this sets a atan whose range is -1 to 1.0

def sigmoid_regularization(raw_value, k=1):
    return torch.sigmoid((raw_value-0.5) * k)

def silu_regularization(raw_value, k=1): # AKA swish function
    return raw_value * torch.sigmoid(raw_value * k)

# k = 10.0
# x = np.linspace(-2.5, 2.5, 500)
# plt.plot(x, np.atan(x * k) / np.pi, label="atan_reg")
# plt.plot(x, 1/(1+(np.exp((-(x-0.5)*k)))), label="sig_reg")
# plt.plot(x, x * 1/(1+(np.exp((-x*k)))), label="silu_reg")
# plt.legend()
# plt.grid()
# plt.show()
# A


#############################################################################
#############################################################################
#############################################################################
#############################################################################

class KANStressPredictor(nn.Module):

    def __init__(self):
        super(KANStressPredictor, self).__init__()

        # n-1
        self.old_kappa = torch.tensor(0.0) # dissipation
        self.old_q = torch.tensor(0.0)     # plastic strain

        self.model_psi = KAN.MultKAN( # eps, q --> psi // stress = grad.psi
            width=[2,  1],
            grid=4,
            k=2,
            grid_range=[0, 1]
        )
        self.model_psi.speed()

        self.model_F = KAN.MultKAN( # stress, kappa --> F
            width=[2, 1],
            grid=4,
            k=2,
            grid_range=[0, 1]
        )
        self.model_F.speed()

    # ----------------------------------------------------------------------------------
    def CalculateStress(self, strain): # returns stress with q and kappa from memory

        psi_KAN_inputs = []
        psi_KAN_inputs.append(strain)
        psi_KAN_inputs.append(torch.full_like(strain, self.old_q))
        KAN_input = torch.cat(psi_KAN_inputs, dim=-1)

        # This method computes the stress without updating internal vars
        # zeros = [torch.zeros_like(strain, requires_grad=True), torch.full_like(strain, self.old_q)]
        # KAN_zeros = torch.cat(zeros, dim=-1) # The null input is at initial configuration
        KAN_zeros = torch.zeros_like(KAN_input, requires_grad=True)

        # PSI is the raw potential from the KAN
        raw_psi = self.model_psi(KAN_input)
        psi_at_0 = self.model_psi(KAN_zeros)

        # Stress is dPSI/dstrain - (dPSI/dstrain)|_{strain=0}
        # The subtraction is necessary to account for the reference state at zero strain,
        # ensuring the stress response is properly shifted (e.g., stress = 0 at strain = 0 if desired by physics)
        grad = torch.autograd.grad(
            outputs=raw_psi,
            inputs=strain,
            grad_outputs=torch.ones_like(raw_psi),
            create_graph=True
        )[0]

        grad_0 = torch.autograd.grad(
            outputs=psi_at_0,
            inputs=KAN_zeros,
            grad_outputs=torch.ones_like(psi_at_0),
            create_graph=True
        )[0]

        return grad - grad_0[:, :1]

    # ----------------------------------------------------------------------------------
    def CalculateSecondDerivativesPsi(self, strain): # d2psi/dE, d2Psi/dE dq
        pass
        # q_for_grad = self.old_q.detach().requires_grad_(True)
        # # Compute psi as function of strain
        # psi_KAN_inputs = []
        # psi_KAN_inputs.append(strain)
        # # psi_KAN_inputs.append(torch.full_like(strain, q_for_grad))
        # psi_KAN_inputs.append(q_for_grad.expand_as(strain))
        # # psi_KAN_inputs.append(torch.full_like(strain, self.old_kappa))

        # KAN_input = torch.cat(psi_KAN_inputs, dim=-1)

        # raw_psi = self.model_psi(KAN_input)

        # # First derivative: stress = d(psi)/d(strain)
        # stress = torch.autograd.grad(
        #     outputs=raw_psi,
        #     inputs=strain,
        #     grad_outputs=torch.ones_like(raw_psi),
        #     create_graph=True,
        # )[0]

        # # Second derivative: C = d(stress)/d(strain) = d²(psi)/d(strain)²
        # C = torch.autograd.grad(
        #     outputs=stress,
        #     inputs=strain,
        #     grad_outputs=torch.ones_like(stress),
        #     create_graph=True)[0]

        # d2Psi_dE_dq = torch.autograd.grad(
        #     outputs=stress,
        #     inputs=q_for_grad,
        #     grad_outputs=torch.ones_like(stress),
        #     create_graph=True)[0]
        
        # return C, d2Psi_dE_dq

    # ----------------------------------------------------------------------------------
    def CalculateFandDerivatives(self, strain):

        stress = self.CalculateStress(strain)
        # keep kappa as internal state, but allow grad for this sensitivity computation
        kappa_for_grad = self.old_kappa.detach().requires_grad_(True)

        F_KAN_inputs = []
        F_KAN_inputs.append(stress) # Stress
        F_KAN_inputs.append(kappa_for_grad.expand_as(strain)) # kappa
        KAN_input = torch.cat(F_KAN_inputs, dim=-1)

        raw_F = self.model_F(KAN_input)

        zeros = [torch.zeros_like(strain, requires_grad=True), torch.full_like(strain, self.old_kappa)]
        KAN_zeros = torch.cat(zeros, dim=-1) # The null input is strain zero and int vars whatever is in memory!
        F_at_zeros = self.model_F(torch.zeros_like(KAN_zeros, requires_grad=True))

        dF_d_stress = torch.autograd.grad(
            outputs=raw_F,
            inputs=stress,
            grad_outputs=torch.ones_like(raw_F),
            create_graph=True,
            retain_graph=True,
            allow_unused=False,
        )[0]

        dF_d_kappa = torch.autograd.grad(
            outputs=raw_F,
            inputs=kappa_for_grad,
            grad_outputs=torch.ones_like(raw_F),
            create_graph=True,
            retain_graph=True,
            allow_unused=False,
        )[0]

        return raw_F - F_at_zeros, dF_d_stress, dF_d_kappa
        # return raw_F, dF_d_stress, dF_d_kappa

    # ----------------------------------------------------------------------------------
    def forward(self, strain):

        strain = strain.detach().requires_grad_(True)

        stress = self.CalculateStress(strain) # predicts with old int vars and curr E

        raw_F, dF_d_stress, dF_d_kappa = self.CalculateFandDerivatives(strain)

        # The sigmoid reg performs the if (F > 0.0) in a soft manner
        dq     = (raw_F / torch.abs(raw_F)) * sigmoid_regularization(raw_F, 50.0) * silu_regularization(dF_d_stress, 50.0)
        dkappa = sigmoid_regularization(raw_F, 50.0) * silu_regularization(dF_d_kappa, 50.0) # SiLU since kappa must increase always

        # scalar internal update to avoid shape mismatch
        self.old_q = (self.old_q + dq.mean()).detach()
        self.old_kappa = (self.old_kappa + dkappa.mean()).detach()

        stress = self.CalculateStress(strain)

        self.old_q = (self.old_q - dq.mean()).detach()
        self.old_kappa = (self.old_kappa - dkappa.mean()).detach()

        return stress

    # ----------------------------------------------------------------------------------
    def FinalizeMaterialResponse(self, strain):

        strain = strain.detach().requires_grad_(True)

        stress = self.CalculateStress(strain) # predicts with old int vars and curr E

        raw_F, dF_d_stress, dF_d_kappa = self.CalculateFandDerivatives(strain)

        # The sigmoid reg performs the if (F > 0.0) in a soft manner
        dq     = (raw_F / torch.abs(raw_F)) * sigmoid_regularization(raw_F, 50.0) * silu_regularization(dF_d_stress, 50.0)
        dkappa = sigmoid_regularization(raw_F, 50.0) * silu_regularization(dF_d_kappa, 50.0) # SiLU since kappa must increase always

        # scalar internal update to avoid shape mismatch
        self.old_q = (self.old_q + dq.mean()).detach()
        self.old_kappa = (self.old_kappa + dkappa.mean()).detach()

    # ----------------------------------------------------------------------------------
    def ResetInternalVars(self):
        self.old_kappa = torch.tensor(0.0) # dissipation
        self.old_q = torch.tensor(0.0)     # plastic strain

#############################################################################
#############################################################################
#############################################################################
#############################################################################

# --------------------
model = KANStressPredictor()
n_epochs = 150
learning_rate = 0.1
# --------------------

# null value at origin check
null_var = torch.tensor([[0.0]], requires_grad=True)
print("Before training: ")
print("model(0)= ", model.CalculateStress(null_var), "\n")

optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)
x_torch = torch.tensor(eps, dtype=torch.float32).unsqueeze(1)  # (steps,1)
y_torch = torch.tensor(sigma, dtype=torch.float32).unsqueeze(1)  # (steps,1)
zeros = torch.zeros_like(x_torch)

for epoch in range(n_epochs):
    optimizer.zero_grad()

    y_pred_list = []
    for i in range(len(x_torch)):
        x_i = x_torch[i].view(1, 1)  # already tensor, no need to recreate
        y_pred_i = model.forward(x_i)        # keep tensor with grad
        y_pred_list.append(y_pred_i)
        model.FinalizeMaterialResponse(x_i)

        # Stack into a tensor
        y_pred = torch.vstack(y_pred_list)  # shape (100,1)

    # L2 loss
    loss = torch.mean((y_pred - y_torch)**2)
    model.ResetInternalVars()

    loss.backward()
    optimizer.step()

    if epoch % 10 == 0:
        print(f"Epoch {epoch}, Loss: {loss.item()}")


# plot the KAN
y_pred_list = []
kappa_list = []
q_list = []
eps = data["eps"][0:100]  # we take the whole dataset for plot
eps = eps / eps_max
x_torch = torch.tensor(eps, dtype=torch.float32).unsqueeze(1)
for i in range(len(x_torch)):
    x_i = x_torch[i].view(1, 1)  # already tensor, no need to recreate
    y_pred_i = model.forward(x_i)        # keep tensor with grad
    model.FinalizeMaterialResponse(x_i)
    y_pred_list.append(y_pred_i)
    kappa_list.append(model.old_kappa)
    q_list.append(model.old_q)
model.ResetInternalVars()

# Convert stacked tensor predictions to numpy
y_pred = torch.vstack(y_pred_list)
kappa_pred = torch.vstack(kappa_list)
kappa_plot = kappa_pred.detach().cpu().numpy()
q_pred = torch.vstack(q_list)
q_plot = q_pred.detach().cpu().numpy()
y_KAN = y_pred.detach().cpu().numpy()

plt.plot(eps, y_KAN, '--', color="k", label='KAN (trained)')
plt.legend()
plt.grid()
plt.show()

# output_file = "KAN_pred.png"
# plt.savefig(output_file, dpi=300, bbox_inches="tight")
# print(kappa_list)
# print(q_list)

plt.plot(eps, kappa_plot, '--', color="k", label='KAN (trained)')
plt.ylabel("Kappa")
plt.show()

plt.plot(eps, q_plot, '--', color="k", label='KAN (trained)')
plt.ylabel("q")
plt.show()

null_var = torch.tensor([[0.0]])
print("After training: ")
print("model(0)= ", model.forward(null_var))
