#!/usr/bin/env python3
"""Plot the two interpretable current-RVE mechanical witnesses.

Inputs are generated by ``mechanics_witnesses.py``.  These graphics deliberately
separate (i) the valid closed-cycle conclusion for Regression from (ii) the
rank-one audit over states with a converged FOM reference.  The OOD Free result
is stated only as an audit boundary, never plotted as an FOM-confirmed failure.
"""
from __future__ import annotations

import json
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np


HERE = Path(__file__).resolve().parent
RESULTS = HERE / "mechanics_witness_results"
FIGURES = RESULTS / "figures"


def load(name: str) -> dict:
    return json.loads((RESULTS / name).read_text())


def save(figure, stem: str) -> None:
    FIGURES.mkdir(parents=True, exist_ok=True)
    for suffix in ("png", "pdf"):
        figure.savefig(FIGURES / f"{stem}.{suffix}", dpi=300, bbox_inches="tight")
    plt.close(figure)


def cycle_figure(audit: dict) -> None:
    cycle = audit["cycle"]
    ordered = ["FOM", "Regression", "Free", "ICNN", "ICKAN"]
    work = np.array([cycle["FOM"]["stress_work_J_per_m3"]] + [
        cycle["models"][name]["stress_work_J_per_m3"] for name in ordered[1:]
    ])
    magnitude = np.abs(work)
    colours = ["#313a46", "#c23b22", "#617a9e", "#1b8a5a", "#704f9f"]

    fig, axis = plt.subplots(figsize=(8.0, 3.6), constrained_layout=True)
    bars = axis.barh(ordered, magnitude, color=colours, height=0.66)
    axis.set_xscale("log")
    axis.set_xlabel(r"$|\oint \mathbf{S}:\mathrm{d}\mathbf{E}|$  [J m$^{-3}$]")
    axis.set_title("Closed multiaxial cycle inside the training box")
    axis.grid(axis="x", which="both", alpha=0.22)
    axis.invert_yaxis()
    for bar, value in zip(bars, work):
        sign = "−" if value < 0 else "+"
        axis.text(bar.get_width() * 1.35, bar.get_y() + bar.get_height() / 2,
                  f"{sign}{abs(value):.2e}", va="center", fontsize=9)
    axis.text(0.01, -0.29,
              "Same closed E11–E22 rectangle; FOM uses 8 and PANNs 16 Gauss points per edge.\n"
              "A hyperelastic law must return zero work. Regression does not have a potential.",
              transform=axis.transAxes, fontsize=9, va="top")
    save(fig, "current_rve_closed_cycle_work")


def rank_one_figure(audit: dict, radial: dict, verification: dict) -> None:
    clouds = audit["rank_one"]["clouds"]
    cloud_names = ["held_out_test", "converged_probe", "uniform_training_box"]
    labels = ["held-out\ntest", "converged\nprobe", "uniform\ntraining box"]
    models = ["Free", "ICNN", "ICKAN"]
    colours = ["#617a9e", "#1b8a5a", "#704f9f"]
    values = np.array([
        [clouds[cloud]["models"][model]["curvature_Pa"] / 1.0e6 for cloud in cloud_names]
        for model in models
    ])

    fig, (left, right) = plt.subplots(1, 2, figsize=(10.3, 3.8),
                                      gridspec_kw={"width_ratios": [1.45, 1]}, constrained_layout=True)
    x = np.arange(len(labels))
    width = 0.23
    for i, (model, colour) in enumerate(zip(models, colours)):
        left.bar(x + (i - 1) * width, values[i], width, label=model, color=colour)
    left.set_xticks(x, labels)
    left.set_ylabel(r"minimum sampled $D^2W[\mathbf{a}\otimes\mathbf{b},\mathbf{a}\otimes\mathbf{b}]$  [MPa]")
    left.set_title("Only domains with a converged FOM reference")
    left.axhline(0.0, color="black", linewidth=0.8)
    left.set_ylim(bottom=0.0)
    left.grid(axis="y", alpha=0.22)
    left.legend(frameon=False, ncol=3, loc="upper center")

    first = radial["free_radial"]["first_negative_by_ring_factor"]
    result = verification["result"]
    right.axis("off")
    right.set_title("What the current RVE does not establish", loc="left")
    lines = [
        "Outward Free-only scan:",
        rf"first sampled negative curvature = {first['curvature_Pa'] / 1e6:.2f} MPa",
        rf"at ring factor {first['ring_factor']:.2f},  det F = {first['det_F']:.3f}",
        "",
        "FOM check:",
        "Newton loses convergence on the",
        "current FOM continuation branch",
        "before reaching this state.",
        "",
        "Therefore this is an OOD warning,",
        "not an FOM-confirmed Free failure.",
    ]
    right.text(0.0, 0.92, "\n".join(lines), va="top", fontsize=10,
               bbox={"boxstyle": "round,pad=0.7", "facecolor": "#f7f3ec", "edgecolor": "#c9b999"})
    if result["converged"]:
        raise RuntimeError("This annotation must be revised: the FOM candidate now converges.")
    save(fig, "current_rve_rank_one_scope")


def main() -> None:
    cycle_audit = load("current_rve_cycle_audit.json")
    rank_one_audit = load("current_rve_mechanics_witnesses.json")
    radial = load("current_rve_free_radial_scan.json")
    verification = load("current_rve_first_negative_fom_verification.json")
    cycle_figure(cycle_audit)
    rank_one_figure(rank_one_audit, radial, verification)
    print(FIGURES)


if __name__ == "__main__":
    main()
