#!/usr/bin/env python3
"""Make compact figures and LaTex macros from a FOM energy-Hessian audit."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np


HERE = Path(__file__).resolve().parent
RESULTS = HERE / "results"
FIGURES = HERE / "figures"


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("--run", type=str, default="h_1.000e-02", help="Results subdirectory to plot.")
    return parser.parse_args()


def tex_num(value: float, digits: int = 3) -> str:
    return f"{value:.{digits}g}"


def tex_escape(text: str) -> str:
    return text.replace("_", r"\_")


def main() -> None:
    args = parse_args()
    run_dir = RESULTS / args.run
    archive = np.load(run_dir / "fom_energy_hessian_audit.npz")
    summary = json.loads((run_dir / "fom_energy_hessian_summary.json").read_text(encoding="utf-8"))
    FIGURES.mkdir(parents=True, exist_ok=True)

    names = [str(name) for name in archive["names"]]
    eig = np.asarray(archive["tangent_eigenvalues"], dtype=float) / 1.0e9
    tangent = np.asarray(archive["tangent_fd"], dtype=float) / 1.0e9

    fig, ax = plt.subplots(figsize=(8.0, 4.2))
    x = np.arange(len(names))
    for j, marker in enumerate(("o", "s", "^")):
        ax.plot(x, eig[:, j], marker=marker, linewidth=1.5, label=fr"$\lambda_{j + 1}$")
    ax.axhline(0.0, color="black", linewidth=0.9)
    ax.set_xticks(x, [name.replace("_", "\n") for name in names])
    ax.set_ylabel(r"Eigenvalues of $\mathbf{D}_E$ [GPa]")
    ax.set_title(r"FOM energy-Hessian audit: $\mathbf{D}_E=\partial^2W/\partial\mathbf{e}^2$")
    ax.grid(axis="y", alpha=0.3)
    ax.legend(ncol=3, fontsize=9)
    fig.tight_layout()
    fig.savefig(FIGURES / "fom_tangent_eigenvalues.pdf", bbox_inches="tight")
    plt.close(fig)

    n = len(names)
    fig, axes = plt.subplots(2, 3, figsize=(10.0, 6.3), constrained_layout=True)
    axes = axes.ravel()
    vmax = float(np.max(np.abs(tangent)))
    for ax, name, matrix in zip(axes, names, tangent):
        image = ax.imshow(matrix, cmap="coolwarm", vmin=-vmax, vmax=vmax)
        ax.set_title(name.replace("_", " "))
        ax.set_xticks(range(3), [r"$E_{11}$", r"$E_{22}$", r"$\gamma_{12}$"])
        ax.set_yticks(range(3), [r"$S_{11}$", r"$S_{22}$", r"$S_{12}$"])
        for i in range(3):
            for j in range(3):
                ax.text(j, i, f"{matrix[i, j]:.2g}", ha="center", va="center", fontsize=7)
    for ax in axes[n:]:
        ax.remove()
    colorbar = fig.colorbar(image, ax=axes[:n], shrink=0.9)
    colorbar.set_label(r"$D_{ij}$ [GPa]")
    fig.savefig(FIGURES / "fom_tangent_matrices.pdf", bbox_inches="tight")
    plt.close(fig)

    records = summary["records"]
    macros = [
        "% Generated by make_fom_tangent_figures.py. Do not edit by hand.",
        rf"\newcommand{{\FomHessianStep}}{{{tex_num(summary['step'])}}}",
    ]
    for record in records:
        key = "".join(piece.capitalize() for piece in record["name"].split("_"))
        macros.append(rf"\newcommand{{\FomMinEig{key}}}{{{tex_num(record['min_eigenvalue'] / 1e9)}\,\mathrm{{GPa}}}}")
    (FIGURES / "fom_tangent_results_macros.tex").write_text("\n".join(macros) + "\n", encoding="utf-8")

    table = [
        r"\begin{tabular}{l c c c}",
        r"\toprule",
        r"State & $[E_{11},E_{22},\gamma_{12}]$ & eigenvalues of $\mathbf{D}_E$ [GPa] & SPD? \\",
        r"\midrule",
    ]
    for record in records:
        e = ", ".join(tex_num(value, 4) for value in record["strain"])
        values = ", ".join(tex_num(value / 1e9, 5) for value in record["tangent_eigenvalues"])
        spd = "yes" if record["is_spd"] else "no"
        table.append(rf"{tex_escape(record['name'])} & $[{e}]$ & $[{values}]$ & {spd} \\")
    table.extend([r"\bottomrule", r"\end{tabular}"])
    (FIGURES / "fom_tangent_results_table.tex").write_text("\n".join(table) + "\n", encoding="utf-8")

    sensitivity_rows = []
    for name in ("extreme_biaxial_shear", "stage10_mixed"):
        paths = [RESULTS / "h_1.000e-02" / name / "state_summary.json", RESULTS / "h_5.000e-03" / name / "state_summary.json"]
        if all(path.exists() for path in paths):
            records_h = [json.loads(path.read_text(encoding="utf-8")) for path in paths]
            sensitivity_rows.append((name, records_h))
    if sensitivity_rows:
        lines = [
            r"\begin{tabular}{l c c c}",
            r"\toprule",
            r"State & $h$ & $\lambda_{\min}(\mathbf{D}_E)$ [GPa] & relative change \\",
            r"\midrule",
        ]
        for name, records_h in sensitivity_rows:
            first = records_h[0]["min_eigenvalue"]
            for j, record in enumerate(records_h):
                change = "--" if j == 0 else tex_num(abs(record["min_eigenvalue"] - first) / abs(first), 3)
                lines.append(
                    rf"{tex_escape(name) if j == 0 else ''} & {tex_num((1e-2, 5e-3)[j], 2)} & "
                    rf"{tex_num(record['min_eigenvalue'] / 1e9, 7)} & {change} \\")
        lines.extend([r"\bottomrule", r"\end{tabular}"])
        (FIGURES / "fom_tangent_sensitivity_table.tex").write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Figures written to {FIGURES}")


if __name__ == "__main__":
    main()
